version: "2"         # required to adjust maintainability checks
plugins:
  eslint:
    enabled: true
    channel: "eslint-6"
  git-legal:
    enabled: true
    config:
      allow_affero_copyleft: false
      allow_strong_copyleft: false
exclude_patterns:
  - "*"
  - "!src/"
checks:
  file-lines:
    config:
      threshold: 750
  method-count:
    config:
      threshold: 30
  method-lines:
    config:
      threshold: 300